// <auto-generated />
using DotNetWebApplication.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetWebApplication.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421203230_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetWebApplication.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 24,
                            DisplayOrder = 2,
                            Email = "Anique1234@gmail.com",
                            Name = "Anique"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            DisplayOrder = 5,
                            Email = "Aliii134@gmail.com",
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            DisplayOrder = 7,
                            Email = "ss789@gmail.com",
                            Name = "Daud"
                        },
                        new
                        {
                            Id = 4,
                            Age = 32,
                            DisplayOrder = 89,
                            Email = "jkls@gmail.com",
                            Name = "Umer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
